ALTER TYPE "OfferingType" ADD VALUE IF NOT EXISTS 'CUSTOM_ORDER';

ALTER TABLE "VendorProfile"
ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT,
ADD COLUMN IF NOT EXISTS "tiktokUrl" TEXT;

ALTER TABLE "Offering"
ADD COLUMN IF NOT EXISTS "messageForPricing" BOOLEAN NOT NULL DEFAULT false;
