ALTER TYPE "StorefrontLayout" ADD VALUE IF NOT EXISTS 'EDITORIAL_SPLIT';
ALTER TYPE "StorefrontLayout" ADD VALUE IF NOT EXISTS 'PORTFOLIO_FIRST';
ALTER TYPE "StorefrontLayout" ADD VALUE IF NOT EXISTS 'BRAND_SPOTLIGHT';
ALTER TYPE "StorefrontLayout" ADD VALUE IF NOT EXISTS 'STOREFRONT_CLASSIC';
