ALTER TYPE "StorefrontFontStyle" ADD VALUE IF NOT EXISTS 'BOLD';
ALTER TYPE "StorefrontFontStyle" ADD VALUE IF NOT EXISTS 'FASHION';
ALTER TYPE "StorefrontFontStyle" ADD VALUE IF NOT EXISTS 'RETRO';
ALTER TYPE "StorefrontFontStyle" ADD VALUE IF NOT EXISTS 'COOL';
